# Generated by Django 4.2.23 on 2025-08-19 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import purchase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('PO_date', models.DateField(default=purchase.models.get_default_po_date)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Partially Received', 'Partially Received'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Draft', max_length=20)),
                ('sales_order_reference', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=50)),
                ('inco_terms', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('notes_comments', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_summary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_file_path', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.IntegerField()),
                ('insufficient_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='purchase.purchaseorder')),
            ],
        ),
    ]
