# Generated by Django 4.2.24 on 2025-09-26 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit_mani', '0002_alter_creditnote_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='credit_note_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
