# Generated by Django 4.2.24 on 2025-09-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_mani', '0003_alter_creditnote_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='invoice',
            new_name='Invoice',
        ),
    ]
