# Generated by Django 4.2.24 on 2025-09-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_mani', '0004_rename_invoice_creditnote_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='Invoice',
            new_name='invoice',
        ),
    ]
