# Generated by Django 4.2.24 on 2025-09-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mani', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
